### PR TITLE
Update youtube ID regex

### PR DESCRIPTION
**Pull request by Pandraghon**
Should match more links : https://regex101.com/r/hUW6zY/1

### CODE REVIEW

**Comment by kyranet** [comment]
You should not touch the ID check: `[a-zA-Z0-9-_]{11}`, as all YouTube IDs have **strictly** that range.
It works. https://regex101.com/r/hUW6zY/3

**Comment by Pandraghon** [comment]
Is `[a-zA-Z0-9_]` more performant than `\w` ?
As far as I'm concerned, `\w` is easier to read.

**Comment by kyranet** [comment]
Should be, as `\w` is an alias of `a-zA-Z`. But the difference is down to nanoseconds. The current RegExp matches nothing in Regex101, can you update the test? ~~Also try with this one link (it uses a `_`, which is uncovered in your RegExp):~~

~~https://www.youtube.com/watch?v=DfTUs-s_XkI~~

Turns out I updated the RegExp but forgot to put the flags `gm` in the RegExp to perform the check.

**Comment by Pandraghon** [comment]
`\w` includes `_`

**Comment by Pandraghon** [comment]
It works : https://regex101.com/r/hUW6zY/7

**Comment by kyranet** [comment]
Althought it's a monolithic RegExp, it seems to be working. It has a little flag in its validation.
image

However, it looks good to me.

**Comment by kyranet** [comment]
Check this one, fixes the issue above. https://regex101.com/r/hUW6zY/8

**Comment by Pandraghon** [comment]
chrome_2017-08-19_01-33-24
wut ?

**Comment by ghost** [comment]
Had the same issue dont know how i fixed it

**Pull request merged**
