### PR TITLE
Added requiredProviders inhibitor

### PR DESCRIPTION
**Pull request by Pandraghon**

### CODE REVIEW

**Comment by Pandraghon** [comment]
Is the exports.help really useful for inhibitors ?

**Comment by CyberiumShadow** [comment]
@kyranet

**Comment by Skillz4Killz** [comment]
From my point of view, it depends on how well you comment your code. If a person like me can understand what the file is doing then it's not but having it there can be useful i believe

**Comment by kyranet** [comment]
Just a little check before actually going to sleep, If I'm not wrong, `exports.help` is being used by the download command to show the description.

**Review by kyranet — APPROVED** [review]
LGTM

**Pull request merged**
