### PR TITLE
did you mean monitor

### PR DESCRIPTION
**Pull request by lmik**
if a command is indicated by the user but not found this calculates the levenshtein distance to all commands and suggests the closest match.

### CODE REVIEW

**Comment by CyberiumShadow** [comment]
@lmik Sorry for Delay.

I'' going to update eslint so I suggest running this through the linter with the pieces lint file once the update is done.

Also, can you move this from monitors to inhibitors and then do the respective changes?

**Comment by UnseenFaith** [comment]
@CyberiumShadow @lmik Correction, this should be in monitors. As for some of the code, you could simplify it by using `msg.guildConf` instead getting the configuration by the function. The only issue I see with the code (maybe, I could be wrong) currently is that it will be running twice (Once in the monitor, and then again after it's rejected)

**Comment by lmik** [comment]
Yeah I agree that this should be a monitor, since it only has to be run when the input did not match any command, while the inhibitor only would be running if it actually detected a command in the first place.

Code is mostly taken from app.js because I was lazy, should I change it?

Also I am running this in this version on my bot right now, no double execution or anything happening!

**Comment by UnseenFaith** [comment]
Correct.

You can change the code if you want, it won't make that big of a difference.

Have you actually tested if there's not a silent double execution? So like log a variable both in your monitor and the app.js (such as prefix length).

**Comment by lmik** [comment]
Just did, and no double execution happening. Where do you see the potential double execution?

**Comment by UnseenFaith** [comment]
As far as Im aware I thought the .catch() in app.js doesn't stop the execution of code. But it might

**Pull request merged**
