### PR TITLE
Fix Music/time command

### PR DESCRIPTION
**Pull request by Pandraghon**
discord_2017-08-22_16-16-07

I cannot test it, right now. 
Can someone do it for me ?

### CODE REVIEW

**Comment by Stitch07** [comment]
Doesn't throw an error, but time always shows as 0.

**Comment by FOG-Yamato** [comment]
Last time I checked the YouTube Data API doesn't return a video length value in the JSON payload, so idk where you're getting that value, if at all.

**Comment by Pandraghon** [comment]
I get that from  https://github.com/fent/node-ytdl-core/blob/fffc10c5c7351aaa15229be753d1f243478d9048/example/info.json#L120

**Comment by kyranet** [comment]
@FOG-Yamato ytdl-core does tell you how many seconds does the song last.

**Comment by kyranet** [comment]
image
Works to me.

**Comment by Pandraghon** [comment]
What about @Soumil07 said ?

**Comment by kyranet** [comment]
You might not be aware of it, but we require Discord.js **Master**, not Stable. And according to the docs (check [StreamDispatcher#time](https://discord.js.org/#/docs/main/master/class/StreamDispatcher?scrollTo=time)), that code is completely valid.

The equation we are doing is

```
SONG_DURATION * 1000 - TIME_PLAYED
```

So, when the song's duration is 100 seconds, it'll be converted to 100000 milliseconds, and TIME_PLAYED (aka StreamDispatcher#time) is the amount of milliseconds the dispatcher has been playing for (do not confuse with totalStreamPlaying which also adds time paused).

Correct me if I am wrong, but that math formula looks perfectly fine to me, and that certain line of code comes from my music bot, which has been working for forever.

**Comment by Pandraghon** [comment]
Ok. Thanks for the explanations, that's what I understood from the documentation.
That's why I didn't figure out the result obtained by Soumil.

**Comment by kyranet** [comment]
He might have forgotten to download the add command.
image

**Comment by Pandraghon** [comment]
Or to clear the current queue.

**Pull request merged**
