### PR TITLE
Added dogfacts without a module.

### PR DESCRIPTION
**Pull request by MrJacz**
Adding another module to do a simple dogfacts command is going to increase memory usage a simple Math.random will do the trick

### CODE REVIEW

**Comment by ghost** [comment]
Codacy please

**Comment by kyranet** [comment]
You're just horribly failing the ESLint tests we have in this repository. And not only Codacy gave you a negative, but Tracis CI also did. Check the ESLint rules from this repository here. https://github.com/dirigeants/komada-pieces/blob/master/.eslintrc.json

**Comment by CyberiumShadow** [comment]
Resolve the ESLint Errors in the next 3 days or this will be closed @MrJacz

**Comment by kyranet** [comment]
Moved to #86

**Pull request closed without merging**
