### PR TITLE
Preperation for Mongo DB Driver 3.0.0

### PR DESCRIPTION
**Pull request by drdrjojo**
Required to work with Mongo DB Native NodeJS Driver 3.0.0

See https://github.com/mongodb/node-mongodb-native/blob/3.0.0/CHANGES_3.0.0.md

### CODE REVIEW

**Review by MrJacz — APPROVED** [review]
Everything seems to be correct here

**Comment by MrJacz** [comment]
Could you pr this into the klasa-pieces repo (tho SGv2 has come about and that needs a complete rewrite it would be nice to be added)

**Comment by kyranet** [comment]
Can you fix the ESLint issues, please?
image

**Review by kyranet — APPROVED** [review]
Checked the changelog, this looks fine to me.

**Pull request merged**
