### PR TITLE
Create dogfacts.js

### PR DESCRIPTION
**Pull request by Stitch07**
Since catfacts is broken, here's an alternative!

### CODE REVIEW

**Comment by kyranet** [comment]
Please check the ESLint errors from the Tracis-CI's report. For future reference, using Komada's ESLint rules will help you uploading pieces without linter issues.

**Comment by CyberiumShadow** [comment]
Resolve the ESLint Errors in the next 3 days or this will be closed

**Comment by CyberiumShadow** [comment]
Resolve the ESLint Errors in the next 3 days or this will be closed @Soumil07

**Comment by kyranet** [comment]
Check ESLint errors, and you should not use these types of comments for that, neither are relevant to the pieces.

**Comment by kyranet** [comment]
Closed the PR due to lack of feedback. And duplicated with #86.

**Pull request closed without merging**
