### PR TITLE
Update purge command

### PR DESCRIPTION
**Pull request by latipun7**
### Changes Proposed in this Pull Request
- Add extended help
- selfbot: false, so I think, no need for `if (client.config.selfbot)
- When user mentioned, it fetches messages up to 100 (discord.js fetchMessages upper limit), then filter msg with author.id = mentioned user, then delete msg from that user X amount.
- When user not mentioned, it simply delete all last X amount of msg.

### (If Applicable) It will fix issues
Not really fixed the issue, but the real issue is, with this code, when I fetch msg (max is 100), then filter it from mentioned user, then delete all msg from that user by X amount (let's say, 100), it will delete all 100 msg from that user in the fetched msg. But, what if in that fetched msg not reached 100 msg of that user? It will return the error ¯\\\_(ツ)_/¯
Well, this is what I can do, I limit the amount from 2 to 25.

Hope there's a better solution. Thank you.

### CODE REVIEW

**Comment by latipun7** [comment]
What about now? Is that legit js code path? 😣

**Comment by kyranet** [comment]
Not yet, you're still parsing arguments manually.

**Comment by tjrgg** [comment]
I'm not sure it's necessary to update this command. Personally, I feel the command is better and cleaner as it is now, without these changes. I'm not even sure what this is changing, honestly. ¯\_(ツ)_/¯

**Comment by latipun7** [comment]
@Tyler0130 , I didn't mean to replace this command, I just want to learn something. So, see? I still don't understand what it means, and maybe that's the basic komada's flow, and I still don't understand what the right to do.

**Comment by jellz** [comment]
I would love this PR to be merged, lol.

**Comment by latipun7** [comment]
Surely you jest, @jellz 😂lol

**Comment by jellz** [comment]
haha

**Review by tjrgg — CHANGES_REQUESTED** [review]
I can't say I would approve these changes. While some changes are appropriate, like changing the permission level, there are several problems with this pull request.

a) arguments are defined when they don't need to be;
b) the error messages in lines 5 and 6 aren't needed since Komada handles these cases internally already;
c) the `bulkDelete` method is called twice; and
d) it doesn't take advantage of await, even though it's an async function.

I would have to recommend changes that correct the above issues before this pull request is considered for merging.

**Pull request closed without merging**
